// Default dropdown options for policy forms
// These are the standard options that can be customized per user in Settings

export const DEFAULT_INSURANCE_COMPANIES = [
  'Life Insurance Corporation of India',
  'Axis Max Life Insurance Limited',
  'HDFC Life Insurance Company Limited',
  'ICICI Prudential Life Insurance Co. Ltd.',
  'Kotak Mahindra Life Insurance Co. Ltd.',
  'IndiaFirst Life Insurance Company Ltd.',
  'Edelweiss Tokio Life Insurance Company Limited',
  'Aegon Life Insurance Co. Ltd.',
  'Aviva Life Insurance Co. India Ltd.',
  'Bajaj Allianz Life Insurance Co. Ltd.',
  'Bharti AXA Life Insurance Co. Ltd.',
  'Canara HSBC Oriental Bank of Commerce Life Insurance Co. Ltd.',
  'IDBI Federal Life Insurance Company Limited',
  'PNB MetLife India Insurance Co. Ltd.',
  'Pramerica Life Insurance Co. Ltd.',
  'Reliance Nippon Life Insurance Company',
  'Sahara India Life Insurance Co. Ltd.',
  'SBI Life Insurance Co. Ltd.',
  'Shriram Life Insurance Company Ltd.',
  'Star Union Dai-ichi Life Insurance Co. Ltd.',
  'Tata AIA Life Insurance Co. Ltd.',
  'Acko General Insurance Ltd.',
  'Agriculture Insurance Company of India Ltd.',
  'Bajaj Allianz General Insurance Co. Ltd.',
  'Cholamandalam MS General Insurance Co. Ltd.',
  'ECGC Ltd. (formerly Export Credit Guarantee Corp.)',
  'Future Generali India Insurance Co. Ltd.',
  'Go Digit General Insurance Ltd.',
  'HDFC ERGO General Insurance Co. Ltd.',
  'ICICI Lombard General Insurance Co. Ltd.',
  'IFFCO-TOKIO General Insurance Co. Ltd.',
  'National Insurance Company Ltd.',
  'New India Assurance Co. Ltd.',
  'Reliance General Insurance Co. Ltd.',
  'Royal Sundaram General Insurance Co. Ltd.',
  'SBI General Insurance Co. Ltd.',
  'Tata AIG General Insurance Co. Ltd.',
  'United India Insurance Company Ltd.',
  'Universal Sompo General Insurance Co. Ltd.',
  'Liberty General Insurance Ltd.',
  'Magma HDI General Insurance Co. Ltd.',
  'Magma General Insurance',
  'Raheja QBE General Insurance Co. Ltd.',
  'Shriram General Insurance Co. Ltd.',
  'Navi General Insurance Ltd.',
  'Zuno General Insurance Ltd. (formerly Edelweiss General)',
  'Kotak Mahindra General Insurance Co. Ltd.',
  'Aditya Birla Health Insurance Co. Ltd.',
  'Care Health Insurance Ltd. (formerly Religare Health)',
  'Galaxy Health Insurance Company Limited (formerly Galaxy Health & Allied)',
  'Narayana Health Insurance Ltd.',
  'Manipal Cigna Health Insurance Company Limited',
  'Niva Bupa Health Insurance Co. Ltd.',
];

export const DEFAULT_PRODUCT_TYPES = [
  'Term Insurance',
  'Whole Life Insurance',
  'Endowment Plan',
  'Money Back Policy',
  'Unit Linked Insurance Plan (ULIP)',
  'Child Education Plan',
  'Child Marriage Plan',
  'Retirement Plan',
  'Pension Plan',
  'Annuity Plan',
  'Guaranteed Return Plan',
  'Savings Insurance Plan',
  'Investment Linked Insurance Plan',
  'Group Life Insurance',
  'Credit Life Insurance',
  'Loan Protection Insurance',
  'Micro Insurance',
  'Keyman Insurance',
  'Individual Health Insurance',
  'Family Floater Health Insurance',
  'Senior Citizen Health Insurance',
  'Group Health Insurance',
  'Critical Illness Insurance',
  'Top-Up Health Insurance',
  'Super Top-Up Health Insurance',
  'Hospital Cash Plan',
  'OPD Insurance',
  'Maternity Insurance',
  'Personal Accident Insurance',
  'Disability Insurance',
  'Two-Wheeler Insurance',
  'Private Car Insurance',
  'Commercial Vehicle Insurance',
  'Third Party Motor Insurance',
  'Comprehensive Motor Insurance',
  'Standalone Own Damage Motor Insurance',
  'Home Insurance',
  'House Structure Insurance',
  'Home Contents Insurance',
  'Rented Home Insurance',
  'Fire Insurance',
  'Property Insurance',
  'Factory Insurance',
  'Shop Insurance',
  'Office Insurance',
  'Warehouse Insurance',
  'Travel Insurance',
  'Domestic Travel Insurance',
  'International Travel Insurance',
  'Student Travel Insurance',
  'Senior Citizen Travel Insurance',
  'Corporate Travel Insurance',
  'Marine Cargo Insurance',
  'Marine Hull Insurance',
  'Export Import Insurance',
  'Business Insurance',
  'SME Insurance',
  'Shopkeeper Insurance',
  'Startup Insurance',
  'Professional Indemnity Insurance',
  'Cyber Insurance',
  'Directors & Officers (D&O) Insurance',
  'Public Liability Insurance',
  'Product Liability Insurance',
  'Workmen Compensation Insurance',
  'Employee Insurance',
  'Crop Insurance',
  'Weather Insurance',
  'Livestock Insurance',
  'Poultry Insurance',
  'Gadget Insurance',
  'Mobile Insurance',
  'Laptop Insurance',
  'Electronics Insurance',
  'Pet Insurance',
  'Event Insurance',
  'Wedding Insurance',
  'Fidelity Guarantee Insurance',
  'Engineering Insurance',
  'Contractor All Risk Insurance',
  'Erection All Risk Insurance',
];

export const DEFAULT_LOBS = [
  'Life Insurance',
  'Health Insurance',
  'Motor Insurance',
  'Fire Insurance',
  'Marine Insurance',
  'Miscellaneous Insurance',
  'Engineering Insurance',
  'Travel Insurance',
  'Liability Insurance',
  'Crop Insurance',
  'Personal Accident Insurance',
];
